language: java
jdk:
- oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: 70c228a3-b82f-4dcf-98dc-40c53d253240
  app: rsoilab1
  on:
    repo: 0co1d/rsoilab1
notifications:
  email: false



